module.exports.UsersModel = require('./users.model')
module.exports.CategoriesModel = require('./categories.model')
module.exports.ArticlesModel = require('./articles.model')
module.exports.MediasModel = require('./medias.model')
module.exports.OAuth2AccessTokensModel = require('./oauth2-access-tokens.model')
module.exports.OAuth2ClientsModel = require('./oauth2-clients.model')
